### ISSUE TITLE
Bullet Bill generator

### ISSUE THREAD

**Issue by master-key-g** [boldowa/GIEPY#10]
I insert are pixi sprite.

# Issue summary 

## Environment information 

- **1.0.1**: 

- **windows 10**: 

## Reproduce procedure 

1. I insert the sprite like you see down but if i now insert bullet bill generator the game freeze.

## Provide minimal list and sprite config file 
00	normal/pixi/ChasinRex.cfg

**Comment by telinc1** [comment]
The issue is almost impossible to understand but I think [the thread which was just posted on SMW Central](https://smwc.me/t/93811) reports the same issue. See my reply to it for a fix which may or may not break everything else.

**Comment by boldowa** [comment]
Thank you for the report.

I confirmed to reproduce in my environment.

## Cause of a problem

Possible causes are two.

1. Misjudged **B**(upper case) and **8** during coding.
2. After copying and pasting, there is a possibility that it was not corrected.

**Comment by telinc1** [comment]
Let me once again mention that I have submitted pull requests (#11 and #12) which fix this issue, as well as another issue with generators.
