### ISSUE TITLE
Missing defines and macros in PIXI compatibility mode

### ISSUE THREAD

**Issue by telinc1** [boldowa/GIEPY#8]
# Issue summary
Using GIEPY in PIXI compatibility mode does not create the `!CustomBit` and `!SprSize` defines, as well as the `%BES()`, `%BEC()`, and `%Between()` macros (all of these are defined in PIXI's [`sa1def.asm`](https://github.com/JackTheSpades/SpriteToolSuperDelux/blob/master/asm/sa1def.asm)).

The `!CustomBit` define has a value of $08 and refers to the bit which must be set in `!extra_bits` for a sprite to be treated as custom. The PIXI compatibility macros seem to assume that groups 2 and 3 are custom, so $08 is probably still correct.

The `!SprSize` define is the number of sprite slots. It is set to $0C (12) on LoROM and $16 (22) on SA-1.

The `%BES()` macro takes a label as an argument and branches to it if the extra bit is set. The `%BEC()` macro is identical, but it branches if the extra bit is clear. The `%LDE()` macro treats groups 1 and 3 as having the extra bit set, so this is probably a safe assumption for those two macros, too.

The `%Between()` macro takes a number and a label. It branches to the label if, as its description notes, A is between the value and the value negated.

## Environment information

- **Program version**: 1.0.1 (also applies to 1.0.0)

- **OS**: Windows 7

## Reproduce procedure

1. Make sure PIXI compatibility mode is enabled and the routines are properly moved
2. Attempt to insert any sprite which relies on any of the above defines and macros, such as the [Fryguy](https://smwc.me/s/16844) from SMW Central (uses the `!SprSize` define)

## Error message

```
FryGuy.asm:153: error: Define !SprSize not found
FryGuy.asm:613: error: Define !SprSize not found
```

## Provide minimal list and sprite config file

A sprite which uses one of the missing defines is, as mentioned above, the [Fryguy](https://smwc.me/s/16844). A lot of other sprites in the SMW Central sprite section use them, too. Additionally, some of PIXI's shared subroutines also use the defines.

The Fryguy spawns itself twice (lines 343 and 407), which requires manual modification to function in-game. Other than that, it can be inserted into any sprite slot of group 2 or 3 (unless the sprite spawning routine is further modified):

```
00:2-3 Fryguy.cfg
```

**Comment by boldowa** [comment]
Thank you for reporting the issue.

I seem to have forgotten those implementations.
